#!/bin/sh

# Apk ain't got this but we can still live without: xcape cowpatty tmate xss-lock languagetool mdcat pdnsd
doas apk add doas-doc xinit xorg-server xorg-server xf86-input-libinput xinit libx11 xf86-input-evdev \
   xsetroot libx11-dev libxft-dev libxinerama-dev setxkbmap xinput xf86-input-synaptics mesa-dri-gallium \
   xf86-video-vesa conky picom xmodmap xmodmap-doc xrandr xrandr-doc libxrandr-dev \
                                                                                                    \
   openrc-doc openrc-user-pam busybox busybox-binsh busybox-doc busybox-extras busybox-extras-openrc \
   busybox-ifupdown busybox-mdev-openrc busybox-openrc busybox-static busybox-suid \
                                                                                                  \
   gnupg gnupg-dirmngr gnupg-doc gnupg-gpgconf gnupg-keyboxd gnupg-lang gnupg-scdaemon gnupg-utils \
   gnupg-wks-client \
                        \
   freetype freetype-doc \
   bash bash-doc make gcc musl-dev linux-headers linux-pam-dev glib git vim htop tmux \
                                                                                                   \
   pipewire pipewire-alsa pipewire-dbg pipewire-dev pipewire-doc pipewire-echo-cancel pipewire-lang \
   pipewire-libs pipewire-openrc pipewire-pulse pipewire-pulse-openrc pipewire-spa-bluez \
   pipewire-spa-tools pipewire-spa-vulkan pipewire-tools pipewire-udev pipewire-zeroconf \
                                                \
   pam-rundir pam-rundir-doc eudev dbus dbus-doc \
   alsa-utils bluez-alsa bluez-alsa-utils bluez alsa-lib-dev alsa-plugins-pulse \
                  \
   acpi acpi-utils \
                                                                                    \
   file cmus ncmpcpp mpd shellcheck jq jq-doc yq-go yq-go-bash-completion xclip entr \
   entr-doc nnn fzf fzf-doc pdfgrep ffmpeg ffmpeg-doc ffplay mpv qemu qemu-doc pandoc-cli imagemagick \
   imagemagick-doc nginx nginx-doc tesseract-ocr tesseract-ocr-data-afr tesseract-ocr-data-eng \
   tesseract-ocr-data-rus gnuplot gnuplot-doc w3m ack ack-doc parallel parallel-doc \
   parallel-bash-completion ack ack-doc asciinema asciinema-doc \
            \
   pfetch-rs \
                    \
   imlib2 imlib2-dev \
                                                \
   man-db man-db-doc texinfo texinfo-doc pkgconf \
                                                                                              \
   usb-modeswitch usb-modeswitch-udev pciutils psutils-doc lshw lshw-doc ddrescue ddrescue-doc \
                      \
   feh scrot flameshot \
                                                                                            \
   perl perl-doc perl-app-cpanminus perl-app-cpanminus-doc perl-local-lib perl-local-lib-doc \
                                                                                                      \
   nmap nmap-doc bmon bmon-doc socat socat-doc openssh openssh-doc ufw ufw-doc tcpreplay tcpreplay-doc \
   dnsmasq dnsmasq-doc tcpflow tcpflow-doc iptables iptables-doc \
   sipcalc sipcalc-doc curl curl-doc networkmanager networkmanager-doc networkmanager-cli \
   modemmanager modemmanager-doc macchanger macchanger-doc tcpdump tcpdump-doc netcat-openbsd \
   netcat-openbsd-doc \
               \
   firefox vimb \
                                                                                                 \
   yt-dlp yt-dlp-bash-completion yt-dlp-core yt-dlp-core-pyc yt-dlp-doc yt-dlp-ejs yt-dlp-ejs-pyc \
   yt-dlp-ejs-rt-nodejs \
                                                                                                     \
   zathura zathura-bash-completion zathura-cb zathura-djvu zathura-doc zathura-lang zathura-pdf-mupdf \
   zathura-ps \
                                                                                                               \
   texlive-dvi texlive texlive-bibtexextra texlive-binextra texlive-context texlive-dbg texlive-dev texlive-doc \
   texlive-fontutils texlive-full texlive-games texlive-humanities texlive-langextra \
   texlive-latexextra texlive-latexrecommended texlive-luatex texlive-mathscience texlive-most \
   texlive-music texlive-pictures texlive-plaingeneric texlive-pstricks texlive-xetex \
                                                                                                  \
   sysstat sysstat-doc e2fsprogs e2fsprogs-doc \
   gptfdisk gptfdisk-doc ntfs-3g ntfs-3g-doc hdparm hdparm-doc dosfstools dosfstools-doc parted \
   parted-doc partclone partclone-doc usbutils usbutils-doc \
                                                                \
   xdg-utils xdg-utils-doc dex dex-doc fontconfig fontconfig-doc \
                                                             \
   nodejs nodejs-doc npm npm-doc pnpm pnpm-doc ts ts-doc yarn \
                                                               \
   pgcli 
   # vagrant aws-cli vulscan dictd kismet reaver
   # docker net-tools net-tools-doc libvirt libvirt-doc bridge-utils bridge-utils-doc
   # In Conflict with other packages: psutils zathura-pdf-poppler

   # pulseaudio pulseaudio-doc pulseaudio-utils pulsemixer pulseaudio-equalizer pulseaudio-alsa pulseaudio-bluez pulseaudio-ctl pulseaudio-openrc pavucontrol


tricky_installations () {
   pg_version=$(apk search postgresql | sed -ne 's/^postgresql\([0-9]\+\)-[0-9].*/\1/p' | sort -n | tail -n1)
   test -n "$pg_version" && doas apk add postgresql${pg_version} postgresql${pg_version}-doc
}

tricky_installations

rc_user_config () {
   # Set up the `user' service for $USER
   doas ln -s /etc/init.d/user /etc/init.d/user.$USER
   doas rc-update add user.$USER

   doas rc-update add alsa
   doas rc-service alsa start

   rc-update  --user add dbus default
   rc-service --user dbus start

   rc-update  --user add pipewire default
   rc-service --user pipewire start
   rc-update  --user add pipewire-pulse default
   rc-service --user pipewire-pulse start

   rc-update  --user add mpd default
   rc-service --user mpd start
}

rc_user_config

doas sh -c 'printf madjou >/etc/hostname'

./misc
./source_down
