#!/usr/bin/env sh

instals ()
{
	npm i -g \
		bashls \
		vscode-langservers-extracted \
		pyright \
		gopls \
		typescript typescript-language-server \
		clangd-12
}

## netbsd packages
cat <<-EOF
EOF

## archlinux packages
cat <<-EOF
		usb_modeswitch vim sudo man
		psutils xorg libglvnd xorg xorg-xinit
		git tmux pulsemixer pulseaudio-alsa pulseaudio-bluetooth
		alsa-utils make gcc pkgconf wget w3m
		lynx htop feh xcb neovim vis kismet
		awk lua perl ffmpeg luarocks
		npm scrot flameshot conky zathura bmon
		zathura-pdf-mupdf zathura-cb zathura-ps xchm
		telegram-desktop bluez bluez-utils openssh dhcp
		wireshark-cli dhclient acpi ntfs-3g
		wifite macchanger iwd libxss pandoc texlive-bin texlive-core
		hashcat cowpatty reaver bully hcxpcapngtool
		xclip texinfo python python-pip dictd
		wpa_supplicant e2fsprogs gptfdisk youtube-dl
		kakoune kak-lsp surfraw xautolock cups
		gutenprint gnuplot usbutils psmisc
		hdparm dosfstools parted
		lsof fzf telegram-desktop sysstat 
		libvirt vagrant qemu dnsmasq ebtables
		xcompmgr cronie imagemagick imagemagick-doc
		texlive-bin hostapd dash tcpdump openbsd-netcat
		pdnsd nmap socat vulscan ufw tcpflow ipcalc sipcalc
		tcpreplay lshw procps-ng bc xinetd partclone ddrescue
		xdg-utils whois bspwm sxhkd xdo urxvt-unicode

		base-devel
		## nxyt: enchant, webkit2gtk, gobject-introspection
		## build-time dependency: sbcl, cl-asdf

		aws-cli atomicparsley docker-scan
EOF

## debian package name
cat <<-EOF
	luarocks npm dictd dict info
	# wayland-protocols libwlroots6 libgles2-mesa-dev libwlroots-dev libinput-dev
EOF


if test -z "$XDG_CONFIG_HOME"; then
	XDG_CONFIG_HOME="$HOME/.config"
	mkdir -p "$XDG_CONFIG_HOME"
fi
if test "$(basename "$PWD")" != simpledots; then
	echo "Error: please run this script from its cwd!"
	exit 1
fi

lbin="$HOME/.local/bin" && mkdir -p "$lbin"
confcopy ()
{
	if test $# -ne 2; then
		echo invalid number of arguments >&2
		return 1
	fi
	local source="$1"
	local destinat="$2"
	test -e "$source" && cp -rv "$source" "$destinat" || return 1
}

confcopy "./tmux/tmux.conf" "$HOME/.tmux.conf"
confcopy "./bash/bashrc" "$HOME/.bashrc"
confcopy "./bash/bashrc0" "$HOME/.bashrc0"
confcopy "./bash/inputrc" "$HOME/.inputrc"
confcopy "./xorg/Xresources" "$HOME/.Xresources"
confcopy "./xorg/xinitrc" "$HOME/.xinitrc"
confcopy "./vim/vimrc" "$HOME/.vimrc"
mkdir -p "$XDG_CONFIG_HOME/zathura/"		&& confcopy "./zathura/zathurarc" "$XDG_CONFIG_HOME/zathura/"
mkdir -p "$XDG_CONFIG_HOME/dunst/"		&& confcopy "./dunst/dunstrc" "$XDG_CONFIG_HOME/dunst/dunstrc"
mkdir -p ~/.dwm					&& confcopy "./dwm/autostart.sh" "$HOME/.dwm"
mkdir -p "$XDG_CONFIG_HOME/conky"		&& confcopy "./conky/conkyrc_*" "$XDG_CONFIG_HOME/conky"
ls scripts/* >/dev/null 2>&1			&& confcopy "scripts/*" "$lbin"
