#!/bin/sh

sudo pacman --noconfirm -Syu                         \
   man texinfo cronie pkgconf usb_modeswitch          \
   pulsemixer pulseaudio-equalizer pulseaudio-alsa     \
   pulseaudio-bluetooth bluez bluez-utils acpi          \
   alsa-utils psutils inetutils coreutils dash           \
   sed grep ack perl cpanminus jq yq nawk tree            \
   lshw psmisc procps-ng bc sysstat e2fsprogs              \
   gptfdisk ntfs-3g hdparm dosfstools parted                \
   partclone xdg-utils dex fontconfig tar xz git             \
   gcc make usbutils mdcat freetype2 imlib2 feh               \
   zathura zathura-pdf-mupdf zathura-cb zathura-ps             \
   xorg xorg-xinit xclip xss-lock xcape                         \
   xorg-xmodmap nmap bmon socat openssh                          \
   openbsd-netcat macchanger tcpdump pdnsd                        \
   ddrescue vulscan ufw tcpreplay dnsmasq lsof                     \
   tcpflow iptables ipcalc sipcalc wget curl whois                  \
   networkmanager modemmanager dictd kismet reaver                   \
   cowpatty htop nnn entr fzf tmux tmate vim scrot                    \
   flameshot pdfgrep gnuplot w3m firefox tesseract                     \
   tesseract-data-afr tesseract-data-eng qemu-desktop                   \
   texlive-bin texlive-core texlive-latexextra texlive-fontsextra        \
   pandoc ffmpeg imagemagick postgresql postgresql-docs pgcli             \
   ncmpcpp mpd conky libvirt parallel bridge-utils                         \
   net-tools pavucontrol mpc unzip shellcheck                               \
   chrony asciinema nginx which languagetool
   # vagrant docker aws-cli nodejs ts-node npm yarn

sudo pacman --noconfirm -Rns xorg-xbacklight && sudo pacman --noconfirm -Syu acpilight
    
# Get webkit version to change surf build config
webkit_version=$(pacman -Ss webkit2gtk | sed -ne 's#extra/webkit2gtk-\([4-9]\.[1-9]\) .*#\1#p')
test -n "$webkit_version" && {
   sudo pacman -Syu gtk3 gcr webkit2gtk-$webkit_version
}

systemctl --user enable pulseaudio
systemctl --user restart pulseaudio
systemctl --user enable mpd
systemctl --user restart mpd
sudo hostnamectl hostname madjou
sudo localectl set-keymap fr
sudo timedatectl set-timezone Africa/Douala
sudo timedatectl set-ntp true
sudo systemctl enable systemd-timesyncd
sudo systemctl restart systemd-timesyncd
#sudo systemctl enable chronyd
#sudo systemctl start chronyd

./misc
./source_down
