#!/bin/sh

# set the desktop session to determine if dwm is running
if test "x$DESKTOP_SESSION" = "x" ; then
	DESKTOP_SESSION='dwm'
	export DESKTOP_SESSION
fi

# XDG_CONFIG_HOME defines the directory relative to which
# user specific configuration should be store, so set it if empty
if test "x$XDG_CONFIG_HOME" = "x" ; then
	XDG_CONFIG_HOME="$HOME/.config"
	export XDG_CONFIG_HOME
	mkdir -p $XDG_CONFIG_HOME
fi

# XDG_CACHE_HOME defines the directory relative to which
# user non-essential files are stored, so set if empty.
if test "x$XDG_CACHE_HOME" = "x" ; then
	XDG_CACHE_HOME="$HOME/.cache"
	export XDG_CACHE_HOME
	mkdir -p $XDG_CACHE_HOME
fi

# setting XDG env variables
XDG_DOWNLOAD_DIR="$HOME/Downloads"  && mkdir -p "$XDG_DOWNLOAD_DIR"    && export XDG_DOWNLOAD_DIR
XDG_PUBLICSHARE_DIR="$HOME/Public"  && mkdir -p "$XDG_PUBLICSHARE_DIR" && export XDG_PUBLICSHARE_DIR
XDG_DOCUMENTS_DIR="$HOME/Documents" && mkdir -p "$XDG_DOCUMENTS_DIR"   && export XDG_DOCUMENTS_DIR
XDG_MUSIC_DIR="$HOME/Music"         && mkdir -p "$XDG_MUSIC_DIR"       && export XDG_MUSIC_DIR
XDG_PICTURES_DIR="$HOME/Pictures"   && mkdir -p "$XDG_PICTURES_DIR"    && export XDG_PICTURES_DIR
XDG_VIDEOS_DIR="$HOME/Videos"       && mkdir -p "$XDG_VIDEOS_DIR"      && export XDG_VIDEOS_DIR

# load all possible xresources configurations
xresources=''
test -r "$HOME/.Xresources" && xresources="$HOME/.Xresources"
test -r "$HOME/.Xdefaults"  && xresources="$xresources $HOME/.Xdefaults"
cat /dev/null $xresources | xrdb -merge -

{
   command -v picom     && picom &
   command -v setxkbmap && setxkbmap -layout fr &
   command -v slstatus  && slstatus &
   command -v conky     && conky -dq -c ~/.config/conky/conky.conf
} >/dev/null 2>&1

#command -v compton >/dev/null \
#   && compton \
#      --shadow-offset-x -20 \
#      --shadow-offset-y -20 \
#      --shadow &

xset 

exec dwm
