#!/bin/sh

# set the desktop session to determine if dwm is running
if test "x$DESKTOP_SESSION" = "x"; then
	DESKTOP_SESSION='dwm'
	export DESKTOP_SESSION
fi

# XDG_CONFIG_HOME defines the directory relative to which
# user specific configuration should be store, so set it if empty
if test "x$XDG_CONFIG_HOME" = "x"; then
	XDG_CONFIG_HOME="$HOME/.config"
	export XDG_CONFIG_HOME
	mkdir -p $XDG_CONFIG_HOME
fi

# XDG_CACHE_HOME defines the directory relative to which
# user non-essential files are stored, so set if empty.
if test "x$XDG_CACHE_HOME" = "x"; then
	XDG_CACHE_HOME="$HOME/.cache"
	export XDG_CACHE_HOME
	mkdir -p $XDG_CACHE_HOME
fi

# setting XDG env variables
XDG_DOWNLOAD_DIR="$HOME/Downloads" && export XDG_DOWNLOAD_DIR
XDG_PUBLICSHARE_DIR="$HOME/Public" && export XDG_PUBLICSHARE_DIR
XDG_DOCUMENTS_DIR="$HOME/Documents" && export XDG_DOCUMENTS_DIR
XDG_MUSIC_DIR="$HOME/Music" && export XDG_MUSIC_DIR
XDG_PICTURES_DIR="$HOME/Pictures" && export XDG_PICTURES_DIR
XDG_VIDEOS_DIR="$HOME/Videos" && export XDG_VIDEOS_DIR

# load all possible xresources configurations
xresources=''
test -r "$HOME/.Xresources" && xresources="$HOME/.Xresources"
test -r "$HOME/.Xdefaults" && xresources="$xresources $HOME/.Xdefaults"
cat /dev/null $xresources | xrdb -merge -

# set keyboard layout to fr
command -v setxkbmap >/dev/null && setxkbmap -layout fr &

# xcompmgr compositor
#command -v xcompmgr >/dev/null \
#   && xcompmgr \
#      -l 0.2 \
#      -t 0.2 \
#      -r 1.7 \
#      -I 0.2 \
#      -O 0.2 \
#      -D 30 \
#      -c \
#      -C \
#      -f &

#command -v picom >/dev/null && picom &
command -v compton >/dev/null \
   && compton \
      --shadow-offset-x -20 \
      --shadow-offset-y -20 \
      --shadow &

command -v slstatus >/dev/null  && slstatus 2>/dev/null &
#command -v conky && conky -q -c ~/.config/conky.conf

# start the window manager
exec dwm
