#!/usr/bin/env sh
#########################
#### tcheukueppo's bashrc

####################
### aliases
####################
alias ll='ls --color=auto -lA'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias et='[ -x /tmp/test ] && /tmp/test'

alias mkft='func_makefast'
alias got='func_goto'

####################
### envar def
####################
PS3='>>> '
PS2='>> '
PS1='\[\e[1;32m(\#\e[0m\]\[\e[1;34m,\e[0m\]\[\e[1;36m\j)\e[0m\] \u\[\e[1;35m@\e[0m\]\h \[\e[1;31m\W\e[0m\] $ '
HISTCONTROL=ignoreboth
HISTSIZE=1000000
HISTFILESIZE=10000000
EDITOR="${EDITOR:-/bin/vim}"

####################
### shell options
####################
shopt -s checkwinsize

####################
### functions
####################

func_apath ()
{
	if printf '%s' "$PATH" | grep -v ":\?${1%%/}/\?\(:\|$\)"; then
		PATH="${PATH:+$PATH:}$1" && export PATH
	fi
}

func_makefast ()
{
	test $# -eq 0 && return 1
	tmp="/tmp/test.$1"
	truncate -s0 $tmp && chmod u+x $tmp
	printf '#!/bin/%s' "$@" > $tmp
	${EDITOR:-vim} $tmp
}

func_goto ()
{
	command -v fzf &>/dev/null || return 1
	eval `history | sed -n 's/^ *[0-9]\+ \+\(.*\)$/\1/p' | grep "^ *cd \+\([/~]\(\w*[/\(\\ \)]*\)*\|'/.\+'\) *$" | sort -u | fzf --layout=reverse`
}

### function call
####################

## append ~/.local/bin to PATH
func_apath "$HOME/.local/bin"

## use tmux on every terminal
command -v wfmux >/dev/null && test -z "$TMUX" && wfmux -f

## NNN's env variables
# Colorscheme
BLK="04" CHR="04" DIR="04" EXE="00" REG="00" HARDLINK="00" SYMLINK="06" MISSING="00" ORPHAN="01" FIFO="0F" SOCK="0F" OTHER="02"
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
# Unique color for each context
# 0-black, 1-red, 2-green, 3-yellow, 4-blue (default), 5-magenta, 6-cyan, 7-white
export NNN_COLORS='4321'
