syntax on
colorscheme onehalflight

" settings
set tabstop=4
set number

" mappings in the insert mode
inoremap ( ()
inoremap " ""
inoremap ' ''
inoremap [ []
inoremap { {}

" highlight groups
hi LineNr ctermfg=White ctermbg=NONE
hi EndOfBuffer ctermbg=NONE
hi Normal ctermbg=NONE
hi Normal guibg=NONE ctermbg=NONE
