syntax on
colorscheme onehalflight

" settings
set number
set relativenumber

set showmatch " highlight the matched text
set ignorecase
set nowrap
set smartcase
set hlsearch
set incsearch

set ruler

set autoindent
set tabstop=3
"set smartindent

" mappings in the insert mode
inoremap ( ()
inoremap " ""
inoremap ' ''
inoremap [ []
inoremap { {}

" highlight groups
hi LineNr ctermfg=White ctermbg=NONE
hi EndOfBuffer ctermbg=NONE
hi Normal ctermbg=NONE
hi Normal guibg=NONE ctermbg=NONE
