syntax on

set tabstop=3
set shiftwidth=3
set expandtab
set number
set directory=/home/kueppo/.vim/swaps
set encoding=utf-8
set nobackup
set nowritebackup
set nowrap
set relativenumber

set updatetime=300

call plug#begin()

"Plug 'lifepillar/vim-gruvbox8'
Plug 'tcheukueppo/xptemplate'

call plug#end()

let g:xptemplate_key = '<C-n>'
let g:gruvbox_transp_bg = 1
let g:gruvbox_filetype_hi_groups = 0

set background=dark
colorscheme gruvbox8_soft

hi Comment ctermfg=3 ctermbg=NONE
hi LineNr ctermfg=3 ctermbg=NONE
hi Normal ctermfg=NONE
